### ISSUE TITLE
1.8 rc2: Sort by folder?

### ISSUE THREAD

**Issue by Leimking** [bkury/skin.night#12]
I have not found a way to sort by folder in skin.night. But I can enable it with another skin and after that it behaves like it should. Maybe there is a way or it has to be added.
Thank you.

**Comment by bkury** [comment]
What version of PHT/PMS and Night are you using?

**Comment by Leimking** [comment]
Plex Home Theater 1.3.5, Night 1.8 rc2.

**Comment by bkury** [comment]
Hmm, can you point me in the direction where I can "enable/activate" this feature in the default plex skin? Have looked through the filters and sort options but I can't find a "sort by folder" option ?

**Comment by Leimking** [comment]
When a movie section is type "Home Videos", you can set it in the list (arrow-left view options). There are "By Folder", "Recently Released", "On Deck", etc.

**Comment by bkury** [comment]
Thanks, just checked it and it's working fine here with Night ... you can access the filter/sort menu via the ContextMenu (keyboard "c"), there you will find Filter/Sort/QuickAction options. (and also "sort by folder" option)

**Comment by Leimking** [comment]
Ah, cool. I never found it, thanks.
