### ISSUE TITLE
Unwatched Crash

### ISSUE THREAD

**Issue by airander** [bkury/skin.night#13]
Looks like when filtering by unwatched, then watching the last unwatched show of one of the shows, it crashes every time.  This started happening after updating to the latest plex pass version.  Was working previously.

**Comment by bkury** [comment]
I will take a look at this but it sounds like a PHT bug. Does this also happen with the default plex skin?

**Comment by bkury** [comment]
Verified, PHT bug .. nothing I can do about it. (reported to plex devs)
