### ISSUE TITLE
Mis-Reporting # of TV Shows and Movies.

### ISSUE THREAD

**Issue by dv8godd** [bkury/skin.night#15]
When going into either area, the Night theme attempts to show the total number of items in that area.  However, it is misreporting this number by being one short.  You can "fix" this by going backwards one click to the end of the list though, effectively adding one to the number when it realizes it's mistake.

For example: When I startup and go into TV Shows, for me it displays 175 shows on page one.  When I page backwards one click to see the end/last page of the list, it updates to 176, which is the proper number.

It does this for both TV and Movies.

I cannot tell if this is a bug in the theme or Plex proper because I don't have another theme that has this feature.

**Comment by bkury** [comment]
PHT provides this information, so there is nothing I can do about it at the skinning level. I will try to replicate and debug this issue directly in PHT and then report it to the plex devs ...
