### ISSUE TITLE
Can I view the TV-Show or Movie Rating on top of the Thumbnail?

### ISSUE THREAD

**Issue by viking2** [bkury/skin.night#17]
In the default skin (Estuary), the TV-Show or Movie Ratings are shown on top of the thumbnail. Can that be done in the Night skin?

**Comment by bkury** [comment]
Have you tried the "overlay" feature?

For widgets:
Preferences --> Widgets --> Overlay 1/2/3/4 --> Rating

Library/Viewmode:
Context Menu --> Left Menu (Appearance / Options) --> Overlays --> Rating --> Apply Changes

**Comment by viking2** [comment]
Ah, Yeah, Thanks!
Is there "instructions" or the Night skin? There is so much to figure out.
Great Skin BTW!

**Comment by bkury** [comment]
No, there are no instructions right now. Best way to learn what's possible with a skin is just to play around to see what everything is doing. If you are stuck or if you have any other question feel free to use the github discussion Q/A section

https://github.com/bkury/skin.night/discussions/categories/q-a

I'll try to answer any questions there.
