### ISSUE TITLE
Hiding Watched TV Shows Hides Watched Episodes 

### ISSUE THREAD

**Issue by viking2** [bkury/skin.night#20]
I would like to hide TV Shows that I have watched, but I do not want to hide watched episodes. However, when I hide the watched TV shows, the watched episodes are also hidden!

Is this a bug or by design?

**The reason is that I want this:**
I always keep the last watched episode in a TV show, and delete the earlier ones. After I have watched the last episode in a TV show I want the TV show, but not episode, hidden. After a new episode is added (and the TV show is now visible), and I have watched the new episode, I want to delete the previous episode. However, this is not possible with the current behavior because the previous episode (and the one just watched) is hidden!  

p.s. I really like your skin! Thank you so much for this!!!"
(Without it, I would stick with Plex + original Night skin).

**Comment by bkury** [comment]
Unfortunately, "Hide Watched" is a KODI function which the skin has no control over.

It may not be exactly what you are looking for but Night has a different "Hide watched" option :
**Context menu --> Appearance (Options) --> Watched (Opacity) --> Set to e.g. 20%**

This feature won't hide your watched content but instead make it transparent.

I also have some other ideas to workaround this issue. I'll test them and get back to you ...
