### ISSUE TITLE
What is the Purpose of "Mark as watched/unwatched"?

### ISSUE THREAD

**Issue by viking2** [bkury/skin.night#21]
What is the Purpose of "Mark as watched/unwatched"?
![](https://i.gyazo.com/91d138fb52796862bbc670591ba02400.png)
Nothing happens after selecting it.

**Comment by bkury** [comment]
Yes, it doesn't do anything anymore. It's basically a leftover from previous/older KODI forks (PLEX, OpenPHT).

I might replace or remove it with the upcoming version, thanks for reporting!
