### ISSUE TITLE
Can I make the playback items stand out more?

### ISSUE THREAD

**Issue by viking2** [bkury/skin.night#24]
When I have hover over an item in the default skin, it is very obvious which item is selected:
![](https://i.gyazo.com/cfff1792d91bc319c79de60d030e67c6.png)

However, in your excellent Night skin, and on my projector screen, I can hardly distinguish which item is selected (it looks fine on my PC monitor though):
![](https://i.gyazo.com/ca7a0e177169d659acc8ec1fb810bb89.png)

Is there any way to make it more obvious, like in the default skin? Maybe also make a colored circle?

TIA!

**Comment by bkury** [comment]
There is a bigger UI update planned after v2.6. Noted, I'll see what I can do ...
