### ISSUE TITLE
Problem with russian fonts

### ISSUE THREAD

**Issue by WillSmith74** [bkury/skin.night#9]
May be this problem linked with unicode porblem. When i choose russian language in settings, almost half of the settings is filled with space characters (empty). Names of the files with russian char also absent (filled space char). Skin: milestone Release: v1.7.3, PlexHT: Version 1.3.5.431-7966a4df. Windows 8.1

**Comment by bkury** [comment]
Hi,

Please update to Night v1.8-rc2 (GIT version) which has unicode support throughout the skin ...

thanks!
